import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NavBar />
                <div className="flex justify-center  min-h-screen">
                    <div className="mx-4 md:mx-10 w-full lg:w-3/4 pt-40 pb-10">{children}</div>
                </div>
                <Footer />
            </body>
        </html>
    );
}
