import LatestBlogs from "@/components/LatestBlogs";
import TechStack from "@/components/TechStack";
import { Name } from "@/constants/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: `${Name}`,
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <>
            <header className=" flex gap-4 flex-col">
                <h1>{Name}</h1>
                <h4 className="text-zinc-400">Full Stack Developer</h4>
            </header>
            <main className="mt-12 flex flex-col gap-8">
                <p>
                    I&apos;m passionate about leveraging technology to solve real-world problems and constantly seeking opportunities to learn and grow in the
                    field of computer science.
                </p>
                <LatestBlogs />
                <TechStack />
            </main>
        </>
    );
}
